name: Jincheng Yang's Home Page
markdown: kramdown
highlighter: rouge
permalink: /users/jcyang/blog/:year/:month/:day/:title
disqus: 
  shortname: jcyang
defaults:
  - scope:
      path: "users/jcyang/assets/files/shorthand-scans"
    values:
      shorthand-scan: true

