name: Jincheng Yang's Home Page
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: blog/:year/:month/:day/:title
disqus: 
  shortname: jcyang
defaults:
  - scope:
      path: ~yang/assets/files/shorthand-scans
    values:
      shorthand-scan: true
baseurl: /